spring.application.name=api-gateway
server.port=8765

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
eureka.client.registry-fetch-interval-seconds=10


spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=movie-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://movie-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/movies/**